
from awesome_panel_extensions.site import Application
from . import authors

ASSETS = (
    "https://github.com/MarcSkovMadsen/awesome-panel-assets/blob/master/awesome-panel/applications/"
)

APPLICATIONS = [
            Application(
                name="Bootstrap Dashboard",
                description="",
                url="bootstrap-dashboard",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/bootstrap_dashboard.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/bootstrap_dashboard/main.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="Custom Bokeh Model",
                description="",
                url="custom-bokeh-model",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/custom_bokeh_model.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/custom_bokeh_model/custom.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="Classic Dashboard",
                description="",
                url="classic-dashboard",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/dashboard.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/dashboard/dashboard.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="DataExplorer - Loading...",
                description="",
                url="data-explorer-loading",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/dataexplorer_loading.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/dataexplorer_loading/dataexplorer_loading.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="DE:TR: Object Detection",
                description="",
                url="detr",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/detr.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/detr/detr.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="ECharts",
                description="",
                url="echarts",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_echarts.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_echarts.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                    "awesome_panel.express",
                ],
            ),
            Application(
                name="Image Classifier",
                description="",
                url="image-classifier",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/image_classifier.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/image_classifier/image_classifier.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="JS Actions",
                description="",
                url="js-actions",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/js_actions.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/js_actions/js_actions.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="Kickstarter Dashboard",
                description="",
                url="kick-starter-dashboard",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/kickstarter_dashboard.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/kickstarter_dashboard/main.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            # Application(
            #     name="Owid Choropleth Map",
            #     description="",
            #     url="owid-choropleth",
            #     thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/owid_choropleth_map.png",
            #     code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/owid_choropleth_map/main.py",
            #     author=authors.MARC_SKOV_MADSEN,
            #     tags=[
            #         "Code",
            #         "App In Gallery",
            #     ],
            # ),
            Application(
                name="Pandas Profiling",
                description="",
                url="pandas-profiling",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/pandas_profiling_app.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/pandas_profiling_app/pandas_profiling_app.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="Param Reference Example",
                description="",
                url="param-reference",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/param_reference_example.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/param_reference_example/param_reference_example.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="Yahoo Query",
                description="",
                url="yahoo-query",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/yahooquery_app.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/yahooquery_app/yahooquery_app.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="Test Bootstrap Alerts",
                description="",
                url="ext-alert",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_bootstrap_alerts.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_bootstrap_alerts.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                    "awesome_panel.express",
                ],
            ),
            Application(
                name="Test Bootstrap Card",
                description="",
                url="ext-card",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_bootstrap_card.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_bootstrap_card.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                    "awesome_panel.express",
                ],
            ),
            Application(
                name="Test Code",
                description="",
                url="ext-code",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_code.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_code.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                    "awesome_panel.express",
                ],
            ),
            Application(
                name="Test DataFrame",
                description="",
                url="ext-dataframe",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_dataframe.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_dataframe.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                    "awesome_panel.express",
                ],
            ),
            Application(
                name="Test Divider",
                description="",
                url="ext-divider",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_divider.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_divider.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                    "awesome_panel.express",
                ],
            ),
            Application(
                name="Test FontAwesome",
                description="",
                url="ext-font-awesome",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_fontawesome.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_fontawesome.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                    "awesome_panel.express",
                ],
            ),
            Application(
                name="Test Headings",
                description="",
                url="ext-headings",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_headings.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_headings.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                    "awesome_panel.express",
                ],
            ),
            Application(
                name="Test Markdown",
                description="",
                url="ext-markdown",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_markdown.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_markdown.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                    "awesome_panel.express",
                ],
            ),
            Application(
                name="Test Material Components",
                description="",
                url="ext-material",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_material_components.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_material.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="Test Model Viewer",
                description="",
                url="ext-model-viewer",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_model_viewer.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_model_viewer.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="Test Perspective Viewer",
                description="",
                url="ext-perspective",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_perspective.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_perspective.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                ],
            ),
            Application(
                name="Test Progress Extension",
                description="",
                url="ext-progress",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_progress_ext.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_progress_ext.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                    "awesome_panel.express",
                ],
            ),
            Application(
                name="Test Social Links",
                description="",
                url="ext-social-links",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_share_links.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_share_links.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                    "awesome_panel.express",
                ],
            ),
            Application(
                name="Test Spinners",
                description="",
                url="ext-spinners",
                thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_spinners.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_spinners.py",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "App In Gallery",
                    "awesome_panel.express",
                ],
            ),
            # Application(
            #     name="Test Wired",
            #     description="",
            #     url="ext-wired",
            #     thumbnail_url="https://github.com/MarcSkovMadsen/awesome-panel/raw/master/assets/images/thumbnails/test_wired.png",
            #     code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/awesome_panel_express_tests/test_wired.py",
            #     author=authors.MARC_SKOV_MADSEN,
            #     tags=[
            #         "Code",
            #         "App In Gallery",
            #         "awesome_panel.express",
            #     ],
            # ),
            Application(
                name="Dialog Template",
                description="An example of a custom Panel Template with a Modal",
                url="dialog-template",
                thumbnail_url="https://raw.githubusercontent.com/MarcSkovMadsen/awesome-panel/master/application/pages/dialog_template/assets/thumbnail.png",
                code_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/dialog_template",
                mp4_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/dialog_template/assets/dialog_template.mp4",
                gif_url="https://github.com/MarcSkovMadsen/awesome-panel/blob/master/application/pages/dialog_template/assets/dialog_template.gif",
                author=authors.MARC_SKOV_MADSEN,
                tags=[
                    "Code",
                    "Awesome Panel",
                    "Shoelace",
                    "Modal",
                ],
            ),
        ]