FROM marcskovmadsen/awesome-panel_base:latest

WORKDIR /app
ADD . ./

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Default port for Azure Web App for containers is 80
# Please note that port and serverPort in the config.toml file
# should correspond to the exposed port
EXPOSE 80

RUN invoke sphinx.copy-from-project-root
WORKDIR /app

ENTRYPOINT [ "/bin/bash", "panel", "serve", "app.py"]