FROM python:3.7.4-slim-stretch

WORKDIR /

# The enviroment variable ensures that the python output is set straight
# to the terminal without buffering it first
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    dpkg-dev \
    gcc

WORKDIR /app

ADD requirements_base.txt ./requirements_base.txt
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements_base.txt \
    && rm -rf requirements_base.txt

ENTRYPOINT [ "/bin/bash" ]