"""# Bootstrap Dashboard Page.

Creates a Bootstrap Dashboard Page with a Chart and a Table

- inspired by the [GetBoostrap Dashboard Template]
(https://getbootstrap.com/docs/4.4/examples/dashboard/)
- implemented using the `awesome_panel' Python package and in particular the
`awesome_panel.express.templates.BootstrapDashboardTemplate`
"""
import pathlib

import awesome_panel.express as pnx
import hvplot.pandas  # pylint: disable=unused-import
import pandas as pd
import panel as pn

from awesome_panel_extensions.site import site

COLOR = "#E1477E"

IMAGE_PATH = (
    pathlib.Path(__file__).parent
    / "assets"
    / "images"
    / "bootstrap_dashboard_template_original.png"
)
DESCRIPTION = """\
The purpose of this app is to test that a **multi-page Dashboard Layout** similar to the [bootstrap dashboard template](https://getbootstrap.com/docs/4.3/examples/dashboard/) from [getboostrap.com](https://getbootstrap.com/) can be implemented in [Panel](https://panel.pyviz.org/).

"""
APPLICATION = site.create_application(
    url="bootstrap-dashboard",
    name="Bootstrap Dashboard",
    author="Marc Skov Madsen",
    description="Demonstrates a Bootstrap styled dashboard with Panel",
    description_long=DESCRIPTION,
    thumbnail="https://raw.githubusercontent.com/MarcSkovMadsen/awesome-panel/master/assets/images/thumbnails/bootstrap_dashboard.png",
    resources = {
        "code": "https://github.com/MarcSkovMadsen/awesome-panel/tree/master/application/pages/bootstrap_dashboard/bootstrap_dashboard.py",
    },
    tags=[
        "Bootstrap",
    ],
)


@site.add(APPLICATION)
def view() -> pn.Column:
    """# Bootstrap Dashboard Page.

    Creates a Bootstrap Dashboard Page with a Chart and a Table

    - inspired by the [GetBoostrap Dashboard Template]
    (https://getbootstrap.com/docs/4.4/examples/dashboard/)
    - implemented using the `awesome_panel' Python package and in particular the
    `awesome_panel.express.templates.BootstrapDashboardTemplate`

    Returns:
        pn.Column -- The Orders View
    """
    table = pn.Pane(
        _get_table_data(),
        sizing_mode="stretch_width",
    )
    pn.config.sizing_mode = "stretch_width"
    main = [
        APPLICATION.intro_section(),
        pn.Column(
            pnx.SubHeader("Dashboard"),
            pn.pane.HoloViews(_holoviews_chart()),
        ),
        pn.Column(
            pnx.SubHeader("Section Title"),
            table,
        ),
    ]
    return pn.template.FastListTemplate(
        title="Bootstrap Dashboard", main=main, main_max_width="800px"
    )


def _holoviews_chart():
    """## Dashboard Orders Chart generated by HoloViews"""
    data = _get_chart_data()
    line_plot = data.hvplot.line(
        x="Day",
        y="Orders",
        height=500,
        line_color=COLOR,
        line_width=6,
    )
    scatter_plot = data.hvplot.scatter(x="Day", y="Orders", height=300,).opts(
        marker="o",
        size=10,
        color=COLOR,
    )
    fig = line_plot * scatter_plot
    gridstyle = {
        "grid_line_color": "black",
        "grid_line_width": 0.1,
    }
    fig = fig.opts(
        responsive=True,
        toolbar=None,
        yticks=list(
            range(
                12000,
                26000,
                2000,
            )
        ),
        ylim=(
            12000,
            26000,
        ),
        gridstyle=gridstyle,
        show_grid=True,
    )
    return fig


def _get_chart_data() -> pd.DataFrame:
    """## Chart Data

    Returns:
        pd.DataFrame -- A DataFrame with dummy data and columns=["Day", "Orders"]
    """

    chart_data = {
        "Day": [
            "Sunday",
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
        ],
        "Orders": [
            15539,
            21345,
            18483,
            24003,
            23489,
            24092,
            12034,
        ],
    }
    return pd.DataFrame(chart_data)


def _get_table_data() -> pd.DataFrame:
    """## Table Data

    Returns:
        pd.DataFrame -- A DataFrame with dummy data and columns=
        ["Header0", "Header1", "Header2", "Header3", "Header4"]
    """

    table_data = [
        (
            1001,
            "Lorem",
            "ipsum",
            "dolor",
            "sit",
        ),
        (
            1002,
            "amet",
            "consectetur",
            "adipiscing",
            "elit",
        ),
        (
            1003,
            "Integer",
            "nec",
            "odio",
            "Praesent",
        ),
        (
            1003,
            "libero",
            "Sed",
            "cursus",
            "ante",
        ),
        (
            1004,
            "dapibus",
            "diam",
            "Sed",
            "nisi",
        ),
        (
            1005,
            "Nulla",
            "quis",
            "sem",
            "at",
        ),
        (
            1006,
            "nibh",
            "elementum",
            "imperdiet",
            "Duis",
        ),
        (
            1007,
            "sagittis",
            "ipsum",
            "Praesent",
            "mauris",
        ),
        (
            1008,
            "Fusce",
            "nec",
            "tellus",
            "sed",
        ),
        (
            1009,
            "augue",
            "semper",
            "porta",
            "Mauris",
        ),
        (
            1010,
            "massa",
            "Vestibulum",
            "lacinia",
            "arcu",
        ),
        (
            1011,
            "eget",
            "nulla",
            "Class",
            "aptent",
        ),
        (
            1012,
            "taciti",
            "sociosqu",
            "ad",
            "litora",
        ),
        (
            1013,
            "torquent",
            "per",
            "conubia",
            "nostra",
        ),
        (
            1014,
            "per",
            "inceptos",
            "himenaeos",
            "Curabitur",
        ),
        (
            1015,
            "sodales",
            "ligula",
            "in",
            "libero",
        ),
    ]
    return pd.DataFrame(
        table_data,
        columns=[
            "Header0",
            "Header1",
            "Header2",
            "Header3",
            "Header4",
        ],
    ).set_index("Header0")


if __name__.startswith("bokeh"):
    view().servable()
